로그 구체화

diff --git a/Specific/Linux/General/.config/sway/src/backend b/Specific/Linux/General/.config/sway/src/backend
--- a/Specific/Linux/General/.config/sway/src/backend
+++ b/Specific/Linux/General/.config/sway/src/backend
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 term=foot
+debug_message=
 
 # This script will helps you without reload your sway program after below codes changed.
 # NOTE: If you want remove or declare new variable, please edit exception handling function at below.
@@ -29,6 +30,7 @@ function power() {
             if [ $input -eq 1 ]; then
                 enter_sleep
                 if [ $? -ne 0 ]; then
+                    debug_message="unable to enter $(enter_sleep 'current'). Please check system configuration to resolve this issue."
                     return $LINENO
                 elif [ -z "$(pgrep -x swaylock)" ]; then
                     ~/.config/sway/src/backend "lock_session"
@@ -70,16 +72,19 @@ function change_wallpaper() {
         fi
     done
 
-    logger --tag sway --priority user.warn 'backend: unable to load wallpaper. please check `~/Pictures/Wallpaper-Bank/wallpapers` directory permission.'
+    debug_message='unable to load swaybg wallpaper. Please check `~/Pictures/Wallpaper-Bank/wallpapers` directory permission.'
     return $LINENO
 }
 
 function lock_session() {
-    if [ -n "$(pgrep -x swaylock)" ]; then return $LINENO; fi
+    if [ -n "$(pgrep -x swaylock)" ]; then
+        debug_message='unable to launch swaylock. swaylock is already running.'
+        return $LINENO
+    fi
 
     target_splash=$(change_wallpaper)
     if [ $? -ne 0 ]; then
-        echo 'unable to load splash image.' >&2
+        debug_message='unable to load swaylock wallpaper. Please check `~/Pictures/Wallpaper-Bank/wallpapers` directory permission.'
         return $LINENO
     fi
     swaylock -elfF --clock -i "$target_splash" --grace 5
@@ -130,8 +135,12 @@ function enter_sleep() {
         enter_sleep 'test'
         if [ $? -eq 0 ]; then
             systemctl sleep
-            if [ $? -ne 0 ]; then return $LINENO; fi
+            if [ $? -ne 0 ]; then
+                debug_message="unable to enter $(enter_sleep 'current'). unknown error occurred."
+                return $LINENO
+            fi
         else
+            debug_message="unable to enter $(enter_sleep 'current'). Please check system configuration to resolve this issue."
             return $LINENO
         fi
     fi
@@ -325,9 +334,9 @@ if [ $# -eq 0 ]; then
 else
     "${@}"
     exit_code=$?
-    if [ $exit_code -gt 5 ]; then #NOTE: Please update this value if you created or deleted any global variables
-        preview=$(cat $0 | nl -b a -n ln | grep -A 7 -B 13 -E "^$exit_code" | sed "/$(expr $exit_code - 1)/s/$/\t\t\t\t\t⟵  BREAKPOINT: exception occurred line $(expr $exit_code - 1)/")
-        echo -e "File $0, line $exit_code, in $@\n$preview" | swaynag -e bottom -y background -lm "backend: An error occurred while executing \`$1\`."
+    if [ $exit_code -gt 8 ]; then #NOTE: Please update this value if you created or deleted any global variables
+        preview=$(cat $0 | nl -b a -n ln | grep -A 4 -B 14 -E "^$(expr $exit_code - 2)" | sed "/$exit_code/s/$/\n ㄴ\t(lldb) [$(date +'%N').$$] \`$1\` function had non-zero exit status/" | sed "/$(expr $exit_code - 2)/s/$/\n ㄴ\t(lldb) [$(date +'%N').$$] BREAKPOINT: exception occurred/")
+        echo -e "File $0, line $(expr $exit_code - 2), in <$@> function\n$preview" | swaynag -e bottom -y background -lm "backend: An error occurred while executing \`$1\` function. reason: $debug_message"
     else
         exit $exit_code
     fi
